services:
  - docker
before_install:
  - docker build -t sain358/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sain358/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-eu-north-1-529917652448"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"